version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
  AWS_SECRET_ACCESS_KEY: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  AWS_REGION: region
  # Algolia
  ALGOLIA_APP_ID: app_id
  ALGOLIA_API_KEY: api_key
  ALGOLIA_INDEX_NAME: index_name
  # Airtable
  AIRTABLE_ACCESS_TOKEN: token
  # Azure
  AZURE_CLIENT_ID: "{{ env_var('AZURE_CLIENT_ID') }}"
  AZURE_CLIENT_SECRET: "{{ env_var('AZURE_CLIENT_SECRET') }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ env_var('AZURE_STORAGE_ACCOUNT_NAME') }}"
  AZURE_TENANT_ID: "{{ env_var('AZURE_TENANT_ID') }}"
  # Chroma
  CHROMA_COLLECTION: collection_name
  CHROMA_PATH: path
  # Clickhouse
  CLICKHOUSE_DATABASE: default
  CLICKHOUSE_HOST: host.docker.internal
  CLICKHOUSE_INTERFACE: http
  CLICKHOUSE_PASSWORD: null
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_USERNAME: null
  # Druid
  DRUID_HOST: hostname
  DRUID_PASSWORD: password
  DRUID_PATH: /druid/v2/sql/
  DRUID_PORT: 8082
  DRUID_SCHEME: http
  DRUID_USER: user
  # DuckDB
  DUCKDB_DATABASE: database
  DUCKDB_SCHEMA: main
  # Google
  GOOGLE_SERVICE_ACC_KEY:
    type: service_account
    project_id: personal-sanbox
    private_key_id: ecbe319e534c9cd3f442f9ef5519904375665a22
    private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDQj8A0neCQRPnl\nMS2DutEjPgdpCWf27JZbOg1nS9EM9H41Ev0j/uuc0JdCD1bi7prSDAfHD6/sXKzc\nzPu9oliAQ8DTckoIPLvcq2UEhKOvry8ch48fqnKV4nhGi9vjh+5H39THUF7xejIR\nMur6okYgNn/Ptlbk4tJOoybrd3TKPhEf18tr+dw6ZwA4tsAVCaVnkhSzsJbjq03Y\nX6LxlzlViqqFScwjjrLnYPlnjDv2Z39+E2TsXf2HZjx1SenSFT0tMweD8CUCp3OB\najuJs6ni7r10qDyGUHY4J1Kb/E8jmeZ+jnpDrq53M7vnhsXqKV2BSZs3o+RDyhbo\nwaIu0Y0bAgMBAAECggEAJeOXpXdxDoSZaXvPqvjLeb2RFxHwYzmD7zrSqItrhRD9\nxKKYfmuXXju+3u9ud3elhLdOymkdKrGDbfGHYmIV9edZJpDCxlBSSLqSdYmrOwV2\nZ5Zw9+29N2GXPCm4XtOZBFGzlCoTtYbfhaRcb///AWclPRUBID/cuRCGx4xCGWNt\nFZGSCczw8yEr8XvMCNFsKexZpyM55s3EOdJxjpRG6CCS6TvX6QR2l+aNM2mzFkec\nNkA4MP4zGI8HevBlNsbAG9BWSiXv2ADopwbAmP43bUaHKZvuL5310DrOuy385Jb8\nKU+lUB3oXqJeVHK+fefcTDr7p1D/aSqvoCkQtt78AQKBgQD2FZBbsiBidZgRgTLN\ntZSpDy3NyOFKTPF2sMedKifmVpVl3sgV1FGDW6UEQM2k8vftMKooPCcfLdcOq8O+\nfzyV8aNHxECySF6h0IX2zzO9ix/M/+NOln/msXa6Vu0Ketj2b4UCEIfwUpqXsBe+\nGd55itPVAuWNs3kr68Sq0xd7AQKBgQDY9yDe51OA5+WHfoqUZZ4/fOQBsUuOmTov\nEA53t2Xq4C3AojuthK8ySk0dJThSd1u8fejnr/KpvX8uQsv17lkK8hoW0gsAugKf\njN4VhCAwNqdS2GKKscHooBdwRtmvKqB/NgubNbSO09JbwnDnB+54tcFVfMKqdcfk\nQvCl/zuUGwKBgQDKk4nY0lPyeZeLoW3vBbGxUjuEkf9UKO8FpBVO/esGpPQrfi/8\nOGI53nGDhM1FInaSHWOV557U/elxvFhRM3DuhpLBe38+xHCSiJQfTwbq2+J74ZJ/\nmUkE4cY5M2HDJMoCZF98CZu+bGGyyVViOu135J7pVY8fDUWMsHOfpFJKAQKBgC/O\n3L5hSMQp1SjzGEQ01Bb3RSKeV6DXYLvIFPgKQHnt5gcBeJb2mshBGRboAa4iQOOa\n9vw+iAEhEWo3K8xINfS0fk0zAVuqoTNZDgK9t34IPPyDU8tt+eVxiVijNApmITGG\nzi3oOp4STNMNWGWAGOseWbiloht/kolYusBJKm6rAoGBALctYTXA6/lHYbCY3Utv\nAXa9tdNMWOpIQJ75ZksEZhI4jZ4j24JJ9+hbT9UQlAKrEZG7ksfrMgeGU3mGdQE5\nthp6SJhH6Tc892FyBVYGFz9aJj8+IcP8Erqr9Ci0M3OSq5dKnPpdDZKcA+55WLfn\nvCMzjD6gFw2rqOeJHZjHKu1V\n-----END PRIVATE KEY-----"
    client_email: pipelines@personal-sanbox.iam.gserviceaccount.com
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://accounts.google.com/o/oauth2/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/your_service_account_email"
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/path/to/your/service/account/key.json"
  GOOGLE_LOCATION: US # Optional
  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://{username}:{password}@{host}:{port}/"
  MONGODB_HOST: host
  MONGODB_PORT: 27017
  MONGODB_USER: user
  MONGODB_PASSWORD: password
  MONGODB_DATABASE: database
  MONGODB_COLLECTION: collection
  # MSSQL
  MSSQL_DATABASE: database
  MSSQL_SCHEMA: schema
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: host
  MSSQL_PASSWORD: password
  MSSQL_PORT: 1433
  MSSQL_USER: SA
  # MySQL
  MYSQL_DATABASE: database
  MYSQL_HOST: host
  MYSQL_PASSWORD: password
  MYSQL_PORT: 3306
  MYSQL_USER: root
  # Pinot
  PINOT_HOST: hostname
  PINOT_PASSWORD: password
  PINOT_PATH: /query/sql
  PINOT_PORT: 8000
  PINOT_SCHEME: http
  PINOT_USER: user
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: megaline
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root
  POSTGRES_HOST: source_db
  POSTGRES_PORT: 5432
  # Qdrant
  QDRANT_COLLECTION: collection
  QDRANT_PATH: path
  # Redshift
  REDSHIFT_SCHEMA: public # Optional
  REDSHIFT_DBNAME: redshift_db_name
  REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  REDSHIFT_PORT: 5439
  REDSHIFT_TEMP_CRED_USER: temp_username
  REDSHIFT_TEMP_CRED_PASSWORD: temp_password
  REDSHIFT_DBUSER: redshift_db_user
  REDSHIFT_CLUSTER_ID: redshift_cluster_id
  REDSHIFT_IAM_PROFILE: default
  # Snowflake
  SNOWFLAKE_USER: username
  SNOWFLAKE_PASSWORD: password
  SNOWFLAKE_ACCOUNT: account_id.region
  SNOWFLAKE_DEFAULT_WH: null                  # Optional default warehouse
  SNOWFLAKE_DEFAULT_DB: null                  # Optional default database
  SNOWFLAKE_DEFAULT_SCHEMA: null              # Optional default schema
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: null      # Optional private key passphrase
  SNOWFLAKE_PRIVATE_KEY_PATH: null            # Optional private key path
  SNOWFLAKE_ROLE: null                        # Optional role name
  SNOWFLAKE_TIMEOUT: null                     # Optional timeout in seconds
  # Trino
  trino:
    catalog: postgresql                       # Change this to the catalog of your choice
    host: 127.0.0.1
    http_headers:
      X-Something: 'mage=power'
    http_scheme: http
    password: mage1337                        # Optional
    port: 8080
    schema: core_data
    session_properties:                       # Optional
      acc01.optimize_locality_enabled: false
      optimize_hash_generation: true
    source: trino-cli                         # Optional
    user: admin
    verify: /path/to/your/ca.crt              # Optional
  # Weaviate
  WEAVIATE_ENDPOINT: https://some-endpoint.weaviate.network
  WEAVIATE_INSTANCE_API_KEY: YOUR-WEAVIATE-API-KEY
  WEAVIATE_INFERENCE_API_KEY: YOUR-OPENAI-API-KEY
  WEAVIATE_COLLECTION: collectionn_name
